services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Kang@2516
      MYSQL_DATABASE: ottshare
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network
    env_file:
      - .env

  app:
    image: seohan02/ottshare:latest
    container_name: ottshare-container
    ports:
      - "8081:8080"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - mysql
      - redis
      - rabbitmq

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  mysql-data: