spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ottshare?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Kang@2516
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange:
    name: chat-topic-exchange
  queue:
    name: chat.user.{userId}
  routing:
    key: room.{roomId}